# generated by OpenAI's GPT-3.5
import random

class Building:
    def __init__(self, name, cost, capacity):
        self.name = name
        self.cost = cost
        self.capacity = capacity

    def produce(self, city):
        """Default: buildings do not produce anything"""
        pass

    def __str__(self):
        return f"{self.name} (Cost: {self.cost}, Capacity: {self.capacity})"

class House(Building):
    def __init__(self):
        super().__init__("House", cost=100, capacity=5)

class Farm(Building):
    def __init__(self):
        super().__init__("Farm", cost=150, capacity=0)

    def produce(self, city):
        food_generated = 10
        city.food += food_generated
        print(f"{self.name} produced {food_generated} food.")

class Factory(Building):
    def __init__(self):
        super().__init__("Factory", cost=300, capacity=0)

    def produce(self, city):
        money_generated = 50
        city.money += money_generated
        print(f"{self.name} produced ${money_generated}.")

class City:
    def __init__(self, name):
        self.name = name
        self.money = 500
        self.food = 50
        self.population = 0
        self.buildings = []

    def add_building(self, building):
        if self.money >= building.cost:
            self.money -= building.cost
            self.buildings.append(building)
            if isinstance(building, House):
                self.population += building.capacity
            print(f"Built a {building.name}.")
        else:
            print("Not enough money to build that.")

    def produce_resources(self):
        for b in self.buildings:
            b.produce(self)

    def status(self):
        print(f"City: {self.name}")
        print(f"Money: ${self.money}, Food: {self.food}, Population: {self.population}")
        print("Buildings:")
        for b in self.buildings:
            print(f" - {b}")

# Sample Gameplay Loop
def game_loop():
    city = City("New Haven")

    actions = {
        "1": House,
        "2": Farm,
        "3": Factory
    }

    for day in range(1, 10):
        print(f"\n--- Day {day} ---")
        city.status()

        print("\nChoose a building to construct:")
        print("1. House ($100)")
        print("2. Farm ($150)")
        print("3. Factory ($300)")
        print("0. Skip building")

        choice = input("Your choice: ").strip()
        if choice in actions:
            city.add_building(actions[choice]())
        else:
            print("No building constructed today.")

        city.produce_resources()

    print("\nGame Over! Final city status:")
    city.status()

if __name__ == "__main__":
    game_loop()
